// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shift.proto

package shift

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CmdMsg_Command int32

const (
	CmdMsg_HealthCheck CmdMsg_Command = 0
	CmdMsg_SetPin      CmdMsg_Command = 1
	CmdMsg_SetByte     CmdMsg_Command = 2
	CmdMsg_Reset       CmdMsg_Command = 3
	CmdMsg_Status      CmdMsg_Command = 4
)

var CmdMsg_Command_name = map[int32]string{
	0: "HealthCheck",
	1: "SetPin",
	2: "SetByte",
	3: "Reset",
	4: "Status",
}

var CmdMsg_Command_value = map[string]int32{
	"HealthCheck": 0,
	"SetPin":      1,
	"SetByte":     2,
	"Reset":       3,
	"Status":      4,
}

func (x CmdMsg_Command) String() string {
	return proto.EnumName(CmdMsg_Command_name, int32(x))
}

func (CmdMsg_Command) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57b45aeee7938714, []int{0, 0}
}

type CmdMsg struct {
	Cmd                  CmdMsg_Command `protobuf:"varint,1,opt,name=cmd,proto3,enum=CmdMsg_Command" json:"cmd,omitempty"`
	Data                 []byte         `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CmdMsg) Reset()         { *m = CmdMsg{} }
func (m *CmdMsg) String() string { return proto.CompactTextString(m) }
func (*CmdMsg) ProtoMessage()    {}
func (*CmdMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_57b45aeee7938714, []int{0}
}

func (m *CmdMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdMsg.Unmarshal(m, b)
}
func (m *CmdMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdMsg.Marshal(b, m, deterministic)
}
func (m *CmdMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdMsg.Merge(m, src)
}
func (m *CmdMsg) XXX_Size() int {
	return xxx_messageInfo_CmdMsg.Size(m)
}
func (m *CmdMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdMsg.DiscardUnknown(m)
}

var xxx_messageInfo_CmdMsg proto.InternalMessageInfo

func (m *CmdMsg) GetCmd() CmdMsg_Command {
	if m != nil {
		return m.Cmd
	}
	return CmdMsg_HealthCheck
}

func (m *CmdMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("CmdMsg_Command", CmdMsg_Command_name, CmdMsg_Command_value)
	proto.RegisterType((*CmdMsg)(nil), "CmdMsg")
}

func init() {
	proto.RegisterFile("shift.proto", fileDescriptor_57b45aeee7938714)
}

var fileDescriptor_57b45aeee7938714 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xce, 0xc8, 0x4c,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xea, 0x66, 0xe4, 0x62, 0x73, 0xce, 0x4d, 0xf1,
	0x2d, 0x4e, 0x17, 0x52, 0xe4, 0x62, 0x4e, 0xce, 0x4d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33,
	0xe2, 0xd7, 0x83, 0x88, 0xea, 0x39, 0xe7, 0xe7, 0xe6, 0x26, 0xe6, 0xa5, 0x04, 0x81, 0xe4, 0x84,
	0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x80, 0x6a, 0x78, 0x82, 0xc0, 0x6c, 0x25,
	0x2f, 0x2e, 0x76, 0xa8, 0x1a, 0x21, 0x7e, 0x2e, 0x6e, 0x8f, 0xd4, 0xc4, 0x9c, 0x92, 0x0c, 0xe7,
	0x8c, 0xd4, 0xe4, 0x6c, 0x01, 0x06, 0x21, 0x2e, 0x2e, 0xb6, 0xe0, 0xd4, 0x92, 0x80, 0xcc, 0x3c,
	0x01, 0x46, 0x21, 0x6e, 0x2e, 0x76, 0x20, 0xdb, 0xa9, 0xb2, 0x24, 0x55, 0x80, 0x49, 0x88, 0x93,
	0x8b, 0x35, 0x28, 0xb5, 0x38, 0xb5, 0x44, 0x80, 0x19, 0xac, 0xa6, 0x24, 0xb1, 0xa4, 0xb4, 0x58,
	0x80, 0x25, 0x89, 0x0d, 0xec, 0x28, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xcf, 0x3d,
	0x01, 0xa3, 0x00, 0x00, 0x00,
}
